source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'chat' do
pod 'Alamofire'
pod "APLSlideMenu"
pod 'CocoaAsyncSocket'
pod 'MagicalRecord'
pod 'SDWebImage'
pod 'Sodium'
pod 'SwiftyJSON'
pod 'TWTToast'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
