source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'chat' do
pod 'Alamofire'
pod "APLSlideMenu"
pod 'CocoaAsyncSocket'
pod 'Heimdall'
pod 'MagicalRecord'
pod 'SDWebImage'
pod 'SwiftyJSON'
pod 'TWTToast'
end
